<?php

/**
 * @file
 * Contains rng_courier.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rng_courier_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rng_courier module.
    case 'help.page.rng_courier':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Courier integration for RNG') . '</p>';
      return $output;

    default:
  }
}
